"""
ANT-RLF/ANTCOL constructive graph coloring.

The implementation follows the ANT-RLF(2, 2) variant described by Costa
and Hertz in "Ants can colour graphs" (JORS, 1997):

1. Each ant builds one maximal independent color class at a time.
2. The first vertex of every class is selected uniformly at random.
3. A later candidate ``v`` is sampled with weight
   ``tau(v, C) ** alpha * eta(v, W) ** beta``, where ``tau`` is the
   average pairwise pheromone between ``v`` and the current class ``C``,
   and ``eta(v, W) = |W| - deg_W(v)`` is the RLF desirability.
4. Every ant reinforces non-adjacent vertex pairs that it put in the same
   class.  An ant using ``k`` colors deposits ``1 / k`` (scaled by ``q``).
5. At the end of an iteration, trails are updated by ``M = rho * M + dM``.

This module intentionally contains no TabuCol/local-search phase.
Paper: https://doi.org/10.1057/palgrave.jors.2600357
"""

from __future__ import annotations

import math
import random
from itertools import combinations
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Set, Tuple

import snap

GRAPH_PATH = "out/ant_ref.txt"
TEMPLATE_GRAPH_PATH = "src/graph.txt"

Coloring = Dict[int, int]
ColorClasses = List[List[int]]
AntSolution = Tuple[Coloring, int, ColorClasses]


class AntRLF:
    """
    Ant-colony graph coloring with an ANT-RLF construction rule.

    ``rho`` is the trail-retention coefficient used in the paper's update
    ``M = rho * M + dM``.  Consequently, the evaporated fraction is
    ``1 - rho``.  With the default ``q=1``, every ant deposits exactly
    ``1 / color_count`` on each same-class vertex pair.

    ``Ant_Ref`` is retained as a backwards-compatible alias because the
    repository benchmark imports that historical misspelling.
    """

    def __init__(
        self,
        graph_name: str = "ant_ref",
        node_num: int = 5,
        edge_prob: float = 0.5,
        alpha: float = 2.0,
        beta: float = 3.0,
        rho: float = 0.5,
        q: float = 1.0,
        ants_per_iteration: int = 20,
        max_iterations: int = 60,
        random_seed: int = 42,
    ):
        self._validate_parameters(
            node_num=node_num,
            edge_prob=edge_prob,
            alpha=alpha,
            beta=beta,
            rho=rho,
            q=q,
            ants_per_iteration=ants_per_iteration,
            max_iterations=max_iterations,
        )

        self.template_graph_path = TEMPLATE_GRAPH_PATH
        self.graph_name = graph_name
        self.graph_path = (
            GRAPH_PATH
            if graph_name == "ant_ref"
            else str(Path("out") / f"{graph_name}.txt")
        )

        if node_num == 0:
            self.graph = snap.TUNGraph.New()
        else:
            edge_count = int(edge_prob * node_num * (node_num - 1) / 2)
            self.graph = snap.GenRndGnm(snap.TUNGraph, node_num, edge_count)

        Path(self.graph_path).parent.mkdir(parents=True, exist_ok=True)
        snap.SaveEdgeList(
            self.graph,
            self.graph_path,
            "Random Undirected Graph Generated by Snap.py",
        )
        print(f"random graph saved to {self.graph_path}")

        self.node_num = node_num
        self.edge_prob = float(edge_prob)
        self.alpha = float(alpha)
        self.beta = float(beta)
        self.rho = float(rho)
        self.q = float(q)
        self.ants_per_iteration = ants_per_iteration
        self.max_iterations = max_iterations
        self.random_seed = random_seed
        self.rng = random.Random(random_seed)

        self.node_ids: List[int] = []
        self.adj: Dict[int, Set[int]] = {}
        self.edges: List[Tuple[int, int]] = []
        self.node_color: Coloring = {}
        self.pheromone: Dict[Tuple[int, int], float] = {}

        self.best_coloring: Coloring = {}
        self.best_color_classes: ColorClasses = []
        self.best_color_count = 0
        self.best_independent_set: List[int] = []
        self.best_iteration = 0
        self.iterations_run = 0
        self.iteration_history: List[Dict[str, int]] = []

        self._rebuild_state()

    @staticmethod
    def _validate_parameters(
        node_num: int,
        edge_prob: float,
        alpha: float,
        beta: float,
        rho: float,
        q: float,
        ants_per_iteration: int,
        max_iterations: int,
    ) -> None:
        if not isinstance(node_num, int) or isinstance(node_num, bool) or node_num < 0:
            raise ValueError("node_num must be a non-negative integer.")
        if not math.isfinite(float(edge_prob)) or not 0.0 <= float(edge_prob) <= 1.0:
            raise ValueError("edge_prob must be between 0 and 1.")
        if not math.isfinite(float(alpha)) or float(alpha) < 0.0:
            raise ValueError("alpha must be a finite non-negative number.")
        if not math.isfinite(float(beta)) or float(beta) < 0.0:
            raise ValueError("beta must be a finite non-negative number.")
        if not math.isfinite(float(rho)) or not 0.0 <= float(rho) <= 1.0:
            raise ValueError("rho must be between 0 and 1.")
        if not math.isfinite(float(q)) or float(q) <= 0.0:
            raise ValueError("q must be a finite positive number.")
        AntRLF._validate_run_count("ants_per_iteration", ants_per_iteration)
        AntRLF._validate_run_count("max_iterations", max_iterations)

    @staticmethod
    def _validate_run_count(name: str, value: int) -> int:
        if not isinstance(value, int) or isinstance(value, bool) or value <= 0:
            raise ValueError(f"{name} must be a positive integer.")
        return value

    def _rebuild_state(self) -> None:
        self.node_ids = sorted(node.GetId() for node in self.graph.Nodes())
        self.node_num = len(self.node_ids)
        self.adj = {node_id: set() for node_id in self.node_ids}
        edge_set: Set[Tuple[int, int]] = set()

        for edge in self.graph.Edges():
            u = edge.GetSrcNId()
            v = edge.GetDstNId()
            if u == v:
                # A self-loop has no feasible proper vertex coloring.  The
                # other algorithms in this repository treat input as simple,
                # so loops are ignored consistently here.
                continue

            self.adj[u].add(v)
            self.adj[v].add(u)
            edge_set.add(self._pair_key(u, v))

        self.edges = sorted(edge_set)
        self._reset_search_state(reset_pheromone=True)

    def _rebuild_internal_state(self) -> None:
        """Backward-compatible name used by the earlier project version."""
        self._rebuild_state()

    def _reset_search_state(self, reset_pheromone: bool = True) -> None:
        self.rng = random.Random(self.random_seed)
        self.node_color = {}
        self.best_coloring = {}
        self.best_color_classes = []
        self.best_color_count = 0 if not self.node_ids else self.node_num + 1
        self.best_independent_set = []
        self.best_iteration = 0
        self.iterations_run = 0
        self.iteration_history = []
        if reset_pheromone:
            self._init_pheromone()

    def reset(self) -> None:
        """Reset the random generator, best solution, history, and trails."""
        self._reset_search_state(reset_pheromone=True)

    def _init_pheromone(self, initial: float = 1.0) -> None:
        if not math.isfinite(float(initial)) or float(initial) < 0.0:
            raise ValueError("initial pheromone must be finite and non-negative.")

        self.pheromone = {
            (u, v): float(initial)
            for u, v in combinations(self.node_ids, 2)
            if v not in self.adj[u]
        }

    @staticmethod
    def _pair_key(u: int, v: int) -> Tuple[int, int]:
        return (u, v) if u < v else (v, u)

    def get_neighbors(self, node_id: int) -> List[int]:
        if node_id not in self.adj:
            print(f"Warning: Node {node_id} does not exist in the graph.")
            return []
        return sorted(self.adj[node_id])

    def _degree_in_subset(self, node_id: int, subset: Set[int]) -> int:
        return len(self.adj[node_id].intersection(subset))

    def _get_pheromone(self, u: int, v: int) -> float:
        if u == v:
            return 1.0
        return self.pheromone.get(self._pair_key(u, v), 0.0)

    def _trace_factor(self, node_id: int, color_class: Sequence[int]) -> float:
        """Return tau(v, C), the mean same-class trail from C to v."""
        if not color_class:
            return 1.0
        return sum(self._get_pheromone(u, node_id) for u in color_class) / len(color_class)

    def _desirability(self, node_id: int, candidates: Set[int]) -> float:
        """ANT-RLF(2,2) desirability: eta(v, W) = |W| - deg_W(v)."""
        return float(len(candidates) - self._degree_in_subset(node_id, candidates))

    def _candidate_weight(
        self,
        node_id: int,
        candidates: Set[int],
        color_class: Sequence[int],
    ) -> float:
        trail = self._trace_factor(node_id, color_class)
        desirability = self._desirability(node_id, candidates)
        try:
            return math.pow(trail, self.alpha) * math.pow(desirability, self.beta)
        except OverflowError:
            return math.inf

    def _roulette_select(self, weighted_nodes: Sequence[Tuple[int, float]]) -> int:
        if not weighted_nodes:
            raise ValueError("weighted_nodes must not be empty.")

        infinite_nodes: List[int] = []
        normalized: List[Tuple[int, float]] = []
        for node_id, raw_weight in weighted_nodes:
            weight = float(raw_weight)
            if math.isinf(weight) and weight > 0.0:
                infinite_nodes.append(node_id)
            elif not math.isfinite(weight) or weight < 0.0:
                normalized.append((node_id, 0.0))
            else:
                normalized.append((node_id, weight))

        if infinite_nodes:
            return self.rng.choice(infinite_nodes)

        max_weight = max(weight for _, weight in normalized)
        if max_weight <= 0.0:
            return self.rng.choice([node_id for node_id, _ in normalized])

        # Dividing by the largest weight preserves the distribution while
        # preventing overflow when several individually finite scores sum.
        scaled = [(node_id, weight / max_weight) for node_id, weight in normalized]
        total = sum(weight for _, weight in scaled)
        threshold = self.rng.random() * total
        cumulative = 0.0
        for node_id, weight in scaled:
            cumulative += weight
            if threshold < cumulative:
                return node_id
        return normalized[-1][0]

    def _select_seed(self, uncolored: Set[int]) -> int:
        """Sigma=2: select the first vertex of a color class uniformly."""
        if not uncolored:
            raise ValueError("Cannot select a seed from an empty set.")
        return self.rng.choice(sorted(uncolored))

    def get_candidate_probabilities(
        self,
        candidates: Iterable[int],
        color_class: Sequence[int],
    ) -> Dict[int, float]:
        """Expose the normalized ANT-RLF transition probabilities."""
        ordered = sorted(set(candidates))
        if not ordered:
            return {}

        candidate_set = set(ordered)
        weighted = [
            (node_id, self._candidate_weight(node_id, candidate_set, color_class))
            for node_id in ordered
        ]
        infinite = [
            node_id
            for node_id, weight in weighted
            if math.isinf(weight) and weight > 0.0
        ]
        if infinite:
            probability = 1.0 / len(infinite)
            return {
                node_id: probability if node_id in infinite else 0.0
                for node_id in ordered
            }

        finite_weights = {
            node_id: max(weight, 0.0) if math.isfinite(weight) else 0.0
            for node_id, weight in weighted
        }
        max_weight = max(finite_weights.values())
        if max_weight <= 0.0:
            probability = 1.0 / len(ordered)
            return {node_id: probability for node_id in ordered}
        scaled = {
            node_id: weight / max_weight
            for node_id, weight in finite_weights.items()
        }
        total = sum(scaled.values())
        return {
            node_id: scaled[node_id] / total
            for node_id in ordered
        }

    def _select_candidate(
        self,
        candidates: Sequence[int],
        color_class: Sequence[int],
        uncolored: Optional[Set[int]] = None,
    ) -> int:
        # ``uncolored`` is accepted for compatibility with the earlier
        # project implementation.  ANT-RLF(2,2) evaluates eta on W, i.e.
        # the feasible candidate set, so no wider set is needed here.
        del uncolored
        ordered = sorted(set(candidates))
        if not ordered:
            raise ValueError("Cannot select from an empty candidate set.")
        candidate_set = set(ordered)
        weighted = [
            (node_id, self._candidate_weight(node_id, candidate_set, color_class))
            for node_id in ordered
        ]
        return self._roulette_select(weighted)

    def _construct_color_class(self, uncolored: Set[int]) -> List[int]:
        """Construct one maximal independent set and remove it from uncolored."""
        if not uncolored:
            return []

        seed = self._select_seed(uncolored)
        color_class = [seed]

        # W contains exactly the uncolored vertices still compatible with
        # every vertex in the current class.  Removing a selected vertex and
        # its W-neighbors incrementally implements the RLF W/B partition.
        candidates = set(uncolored)
        candidates.discard(seed)
        candidates.difference_update(self.adj[seed])

        while candidates:
            selected = self._select_candidate(
                sorted(candidates),
                color_class,
                uncolored,
            )
            color_class.append(selected)
            candidates.discard(selected)
            candidates.difference_update(self.adj[selected])

        uncolored.difference_update(color_class)
        return color_class

    def _construct_one_solution(self) -> AntSolution:
        uncolored = set(self.node_ids)
        coloring: Coloring = {}
        color_classes: ColorClasses = []

        while uncolored:
            color_class = self._construct_color_class(uncolored)
            if not color_class:
                raise RuntimeError("ANT-RLF failed to construct a color class.")
            color_id = len(color_classes) + 1
            for node_id in color_class:
                coloring[node_id] = color_id
            color_classes.append(color_class)

        return dict(sorted(coloring.items())), len(color_classes), color_classes

    def _build_color_classes(self, coloring: Coloring) -> ColorClasses:
        buckets: Dict[int, List[int]] = {}
        for node_id, color_id in coloring.items():
            buckets.setdefault(color_id, []).append(node_id)
        return [sorted(buckets[color_id]) for color_id in sorted(buckets)]

    def _is_valid_coloring(self, coloring: Coloring) -> bool:
        return self.is_valid_coloring(coloring)

    def _update_pheromone(
        self,
        ant_solutions,
        color_count: Optional[int] = None,
    ) -> None:
        """
        Apply the paper's colony update ``M = rho*M + dM``.

        Internally, ``ant_solutions`` is a sequence of full AntSolution
        tuples, so every ant contributes.  ``(color_classes, color_count)``
        is also accepted for compatibility with the former private method.
        """
        if color_count is None:
            solutions = list(ant_solutions)
        else:
            solutions = [({}, color_count, [list(cls) for cls in ant_solutions])]

        delta: Dict[Tuple[int, int], float] = {}
        for _, solution_color_count, color_classes in solutions:
            if solution_color_count <= 0:
                continue
            deposit = self.q / solution_color_count
            for color_class in color_classes:
                for u, v in combinations(color_class, 2):
                    key = self._pair_key(u, v)
                    if key in self.pheromone:
                        delta[key] = delta.get(key, 0.0) + deposit

        for key, old_value in list(self.pheromone.items()):
            self.pheromone[key] = self.rho * old_value + delta.get(key, 0.0)

    def solve(
        self,
        max_iterations: Optional[int] = None,
        ants_per_iteration: Optional[int] = None,
        verbose: bool = False,
    ) -> Tuple[Coloring, int]:
        iterations = self.max_iterations if max_iterations is None else max_iterations
        ants = self.ants_per_iteration if ants_per_iteration is None else ants_per_iteration
        iterations = self._validate_run_count("max_iterations", iterations)
        ants = self._validate_run_count("ants_per_iteration", ants)

        # A solve call represents a fresh reproducible colony run.
        self._reset_search_state(reset_pheromone=True)

        if not self.node_ids:
            self.best_color_count = 0
            self.node_color = {}
            return {}, 0

        for iteration in range(1, iterations + 1):
            ant_solutions: List[AntSolution] = []

            for _ in range(ants):
                solution = self._construct_one_solution()
                coloring, solution_color_count, color_classes = solution
                if not self._is_valid_coloring(coloring):
                    raise RuntimeError("ANT-RLF constructed an invalid coloring.")

                ant_solutions.append(solution)

                if solution_color_count < self.best_color_count:
                    self.best_coloring = dict(coloring)
                    self.best_color_count = solution_color_count
                    self.best_color_classes = [list(cls) for cls in color_classes]
                    self.best_iteration = iteration

                for color_class in color_classes:
                    if len(color_class) > len(self.best_independent_set):
                        self.best_independent_set = list(color_class)

            iteration_best = min(solution[1] for solution in ant_solutions)
            self._update_pheromone(ant_solutions)
            self.iterations_run = iteration
            self.iteration_history.append(
                {
                    "iteration": iteration,
                    "iteration_best": iteration_best,
                    "global_best": self.best_color_count,
                }
            )

            if verbose:
                print(
                    f"[Iter {iteration}] iteration_best={iteration_best}, "
                    f"global_best={self.best_color_count}"
                )

        if not self.best_coloring:
            raise RuntimeError("Failed to construct a feasible coloring.")

        self.node_color = dict(sorted(self.best_coloring.items()))
        return dict(self.node_color), self.best_color_count

    def color_graph(
        self,
        max_iterations: Optional[int] = None,
        ants_per_iteration: Optional[int] = None,
        verbose: bool = False,
    ) -> Tuple[Coloring, int]:
        return self.solve(
            max_iterations=max_iterations,
            ants_per_iteration=ants_per_iteration,
            verbose=verbose,
        )

    def count_conflicting_edges(self, coloring: Optional[Coloring] = None) -> int:
        current = self.node_color if coloring is None else coloring
        return sum(
            1
            for u, v in self.edges
            if u in current and v in current and current[u] == current[v]
        )

    def is_valid_coloring(self, coloring: Optional[Coloring] = None) -> bool:
        current = self.node_color if coloring is None else coloring
        return (
            set(current) == set(self.node_ids)
            and self.count_conflicting_edges(current) == 0
        )

    def used_colors(self) -> List[int]:
        return sorted(set(self.node_color.values()))

    def get_state(self) -> Dict[str, object]:
        pheromone_values = list(self.pheromone.values())
        return {
            "colors": dict(self.node_color),
            "used_colors": self.used_colors(),
            "color_count": len(self.used_colors()),
            "conflicting_edges": self.count_conflicting_edges(),
            "valid_coloring": self.is_valid_coloring(),
            "best_color_count": (
                self.best_color_count if self.best_coloring or not self.node_ids else None
            ),
            "best_independent_set": list(self.best_independent_set),
            "best_iteration": self.best_iteration,
            "iterations_run": self.iterations_run,
            "pheromone_pairs": len(self.pheromone),
            "pheromone_min": min(pheromone_values) if pheromone_values else None,
            "pheromone_max": max(pheromone_values) if pheromone_values else None,
            "alpha": self.alpha,
            "beta": self.beta,
            "rho": self.rho,
        }

    def print_result(self) -> None:
        if set(self.node_color) != set(self.node_ids):
            print("No coloring result.")
            return

        print(f"colors used: {len(self.used_colors())}")
        print(f"conflicting edges: {self.count_conflicting_edges()}")
        for node_id in sorted(self.node_color):
            print(f"node {node_id}, color {self.node_color[node_id]}")

    def load_graph(self, file_path: str) -> None:
        self.graph = snap.LoadEdgeList(snap.PUNGraph, file_path, 0, 1)
        self._rebuild_state()
        print(f"load graph from {file_path}")

    def save_graph(self, file_path: str) -> None:
        snap.SaveEdgeList(self.graph, file_path, "Undirected Graph Saved")
        print(f"graph saved to {file_path}")


def import_template_graph():
    return snap.LoadEdgeList(snap.PUNGraph, TEMPLATE_GRAPH_PATH, 0, 1)


def draw_graph(graph) -> None:
    # Visualization is optional; keep the coloring algorithm importable in
    # benchmark environments that install SNAP but not plotting packages.
    import matplotlib.pyplot as plt
    import networkx as nx

    nx_graph = nx.Graph()
    nx_graph.add_nodes_from(node.GetId() for node in graph.Nodes())
    for edge in graph.Edges():
        if edge.GetSrcNId() != edge.GetDstNId():
            nx_graph.add_edge(edge.GetSrcNId(), edge.GetDstNId())

    nx.draw(nx_graph, with_labels=True)
    plt.show()


# Canonical and backwards-compatible class names.
Ant_RLF = AntRLF
ant_rlf = AntRLF


def test_class() -> None:
    agent = AntRLF(ants_per_iteration=10, max_iterations=20, random_seed=7)
    agent.load_graph(TEMPLATE_GRAPH_PATH)
    agent.solve(verbose=True)
    agent.print_result()


def main() -> None:
    test_class()


if __name__ == "__main__":
    main()
