"""
template https://snap.stanford.edu/snappy/doc/tutorial/tutorial.html#basic-types

G1 = snap.TUNGraph.New()
G1.AddNode(1)
G1.AddNode(5)
G1.AddNode(32)


G1.AddEdge(1,5)
G1.AddEdge(5,1)
G1.AddEdge(5,32)

G2 = snap.GenRndGnm(snap.TUNGraph, 20, 50)

import networkx as nx
import matplotlib.pyplot as plt

# 将Snap图转换为NetworkX图
G = nx.Graph()
for EI in G2.Edges():
    G.add_edge(EI.GetSrcNId(), EI.GetDstNId())

# 绘制图
nx.draw(G, with_labels=True)
plt.show()

"""
from networkx.classes import neighbors

"""
思路， 针对于每一个顶点 一个improve_payoff 方法

遍历顶点
improve_payoff
    两种初始状态都是看看 颜色1-n 或者 全是0
check_nash_equilibrium 
    -> nash  -> end
-> next vertex

"""
import snap
import random
import networkx as nx
import matplotlib.pyplot as plt

GRAPH_PATH = "out/graph.txt"
TEMPLATE_GRAPH_PATH = "src/graph.txt"


class coloring_game():
    def __init__(self, node_num: int = 5, edge_prob: float = 0.5, node_mode = 0, random_seed = 42):

        self.template_graph_path = TEMPLATE_GRAPH_PATH

        self.graph = snap.GenRndGnm(snap.TUNGraph, node_num, int(edge_prob * node_num * (node_num - 1) / 2))

        snap.SaveEdgeList(self.graph, GRAPH_PATH, "Random Undirected Graph Generated by Snap.py")
        print(f"random graph saved to {GRAPH_PATH}")

        # assure all vectors are colored as 0
        # 后期换一下比较
        self.node_num = node_num
        self.edge_prob = edge_prob
        self.color_mode = 0
        self.node_color = [0] * (node_num + 1) # 0 的位置不用
        self.node_mode = node_mode # 0-> 1,2,3   1-> 3,2,1   2->random
        self.traverse_mode = "forward" # dfs, bfs, random forward reverse
        self.random_seed = random_seed
        self.current_payoff = [-1] * (node_num + 1)

    def init_coloring(self, color_mode: int = 0):
        """
        color_mode: 0 -> all 0, 1 -> [1, 2, 3 ...]
        """
        self.color_mode = color_mode

        coloring = [0] * self.node_num
        if color_mode:
            coloring = list(range(1, self.node_num + 1))

        for i in range(self.node_num):
            self.node_color[i] = coloring[i]

    def get_one_node(self):
        node_mode = self.node_mode

        if node_mode == 0:
            return self.graph.BegNI()
        elif node_mode == 1:
            return self.graph.EndNI()

        Rnd = snap.TRnd(self.random_seed)
        Rnd.Randomize()
        return self.graph.GetRndNI(Rnd)

    def get_neighbors(self, node_id: int):
        """
        获取与指定 node_id 有连接的所有其他节点的 ID 列表
        """
        neighbors = []

        # 确保图中存在该节点
        if not self.graph.IsNode(node_id):
            print(f"Warning: Node {node_id} does not exist in the graph.")
            return neighbors

        # 获取对应的节点迭代器 (Node Iterator)
        node = self.graph.GetNI(node_id)

        # 遍历该节点的所有连接 (Degree)
        # 对于无向图(TUNGraph)，GetOutNId(i) 返回的就是第i个连接的邻居ID
        for i in range(node.GetDeg()):
            neighbor_id = node.GetOutNId(i)
            neighbors.append(neighbor_id)

        return neighbors

    def get_payoff(self, node_id):
        """
        return how many nodes have the same color with node_id's color, as payoff
        """

        # safe check
        if node_id > self.node_num or node_id < 0:
            print(f"Get payoff check: Node {node_id} does not exist in the graph.")
            exit(-1)

        return self.node_color.count(self.node_color[node_id]) - 1

    def have_same_color_with_neighbours(self, node_id, color_id):
        """
        if 相邻的顶点有相同颜色 return Ture
        """
        neighbors = self.get_neighbors(node_id)
        for neighbor in neighbors:
            # print(f"node id {node_id}, neighbor id {neighbor}")
            if self.node_color[neighbor] == color_id:
                return True
            
        return False

    def improve_payoff(self, node_id):
        """
        1. 获取当前payoff
        2. 改变颜色 获取改变颜色后payoff
        3. 比较大小  yes 保存改变的颜色
                    no 再次改变颜色
                    end 无法提高 payoff
        """
        # safe check
        if node_id < 0 or node_id > self.node_num:
            print(f"node num {self.node_num}")
            print(f"Improve payoff check: Node {node_id} does not exist in the graph.")
            return -1

        current_payoff = self.current_payoff[node_id]
        original_color = self.node_color[node_id]

        for new_color in range(self.node_num + 1):
            if new_color == original_color:
                continue

            if self.have_same_color_with_neighbours(node_id, new_color):
                continue

            # 2. 改变颜色
            self.node_color[node_id] = new_color

            # 获取改变颜色后的 payoff
            new_payoff = self.get_payoff(node_id)

            # 如果和周围颜色相同或者可以改进payoff，那么改变颜色
            if new_payoff > current_payoff:
                # yes 保存改变的颜色 (直接退出函数，返回 True 表示发生改变)
                # self.node_color[node_id] = new_color
                self.current_payoff[node_id] = new_payoff
                return True

            # no 再次改变颜色 (通过 for 循环自动进入下一种颜色的尝试)

            self.node_color[node_id] = original_color

        return False

    def set_node_mode(self, node_mode = 0, random_seed = 42):
        self.node_mode = node_mode
        self.random_seed = random_seed

    def set_traverse_mode(self, traverse_mode="forward"):
        self.traverse_mode = traverse_mode

    def get_traverse_sequence(self, start_node_id):
        """
        根据 traverse_mode 遍历所有节点，返回依次访问的节点 id 列表
        """
        nodes = [node.GetId() for node in self.graph.Nodes()]

        if self.traverse_mode == "forward":
            # 升序排列后，找到起点索引，做环形拼接
            sorted_nodes = sorted(nodes)
            idx = sorted_nodes.index(start_node_id)
            return sorted_nodes[idx:] + sorted_nodes[:idx]

        elif self.traverse_mode == "reverse":
            # 降序排列后，找到起点索引，做环形拼接
            sorted_nodes = sorted(nodes, reverse=True)
            idx = sorted_nodes.index(start_node_id)
            return sorted_nodes[idx:] + sorted_nodes[:idx]

        elif self.traverse_mode == "random":
            # 随机模式：保证 start_node_id 是第一个，剩余节点打乱
            rng = random.Random(self.random_seed)
            other_nodes = [n for n in nodes if n != start_node_id]
            rng.shuffle(other_nodes)
            return [start_node_id] + other_nodes

        elif self.traverse_mode == "bfs":
            visited = {start_node_id}
            queue = [start_node_id]
            seq = []
            while queue:
                curr = queue.pop(0)
                seq.append(curr)
                for nbr in self.get_neighbors(curr):
                    if nbr not in visited:
                        visited.add(nbr)
                        queue.append(nbr)
            # 处理非连通图孤立节点
            seq.extend([n for n in nodes if n not in visited])
            return seq

        elif self.traverse_mode == "dfs":
            visited = set()
            seq = []

            def dfs(nid):
                visited.add(nid)
                seq.append(nid)
                for nbr in self.get_neighbors(nid):
                    if nbr not in visited:
                        dfs(nbr)

            dfs(start_node_id)
            # 处理非连通图孤立节点
            seq.extend([n for n in nodes if n not in visited])
            return seq

        else:
            print(f"Warning: Traverse mode {self.traverse_mode} not supported.")
            exit(-1)

    def move_to_nash_equilibrium(self):
        """
        对于所有顶点 遍历 improve_payoff
        flag 是否改变过颜色    直到一次整个遍历没有改变颜色
        """
        # 如果对比还是不够的话 可以每一轮都改一个start node
        start_node = self.get_one_node()
        start_node_id = start_node.GetId()
        color_change_flag = False
        traverse_seq = self.get_traverse_sequence(start_node_id)
        iterations = 0
        # 现在的遍历是 随机/首/尾 顶点开始  逐一往后 对比的时候可以再加一个随机便利
        # 首先完成首-> 末尾的
        while 1:
            for node_id in traverse_seq:
                color_change_flag = self.improve_payoff(node_id)
            iterations += 1

            # 如果整轮遍历结束后，没有节点改变颜色，说明已达到纳什均衡
            print(f"iterations: {iterations}")
            self.print_result()

            if not color_change_flag:
                print(f"Nash Equilibrium reached after {iterations} iterations.")
                break

    def print_result(self):
        for node_id in range(1, self.node_num + 1):
            print(f"node {node_id}, color {self.node_color[node_id]}")
        max_payoff = sum(self.current_payoff)
        print(f"max payoff: {max_payoff}")

    def load_graph(self, file_path: str):
        self.graph = snap.LoadEdgeList(snap.PUNGraph, file_path, 0, 1)
        self.node_num = self.graph.GetNodes()

        self.node_color = [0] * (self.node_num + 1)
        self.current_payoff = [-1] * (self.node_num + 1)

        print(f"load graph from {file_path}")

    def save_graph(self, file_path: str):
        snap.SaveEdgeList(self.graph, file_path, "Undirected Graph Saved")
        print(f"graph saved to {GRAPH_PATH}")

def import_template_graph():
    file_path = "src/graph.txt"
    G = snap.LoadEdgeList(snap.PUNGraph, file_path, 0, 1)
    return G

def draw_graph(graph):

    G = nx.Graph()
    for EI in graph.Edges():
        G.add_edge(EI.GetSrcNId(), EI.GetDstNId())

    nx.draw(G, with_labels=True)
    plt.show()

def main():
    G = import_template_graph()
    draw_graph(G)

def test_class():
    agent = coloring_game()
    agent.load_graph(TEMPLATE_GRAPH_PATH)
    agent.move_to_nash_equilibrium()
    agent.print_result()

if __name__ == '__main__':
    main()
    test_class()
