import random
from typing import Dict, List, Optional

import matplotlib.pyplot as plt
import networkx as nx
import snap

GRAPH_PATH = "out/graph.txt"
TEMPLATE_GRAPH_PATH = "src/graph.txt"


class coloring_game:
    """
    Selfish-improvement graph coloring game from
    "Playing a Game to Bound the Chromatic Number".

    Vertices are players. Every player can choose one of the color labels.
    A vertex gets payoff 0 if any neighbor has the same color; otherwise its
    payoff is the number of vertices currently using the same color.
    """

    def __init__(
        self,
        node_num: int = 5,
        edge_prob: float = 0.5,
        node_mode: int = 0,
        random_seed: int = 42,
    ):
        self.template_graph_path = TEMPLATE_GRAPH_PATH
        self.graph = snap.GenRndGnm(
            snap.TUNGraph,
            node_num,
            int(edge_prob * node_num * (node_num - 1) / 2),
        )
        snap.SaveEdgeList(self.graph, GRAPH_PATH, "Random Undirected Graph Generated by Snap.py")
        print(f"random graph saved to {GRAPH_PATH}")

        self.node_num = node_num
        self.edge_prob = edge_prob
        self.color_mode = 1
        self.node_mode = node_mode
        self.traverse_mode = "forward"
        self.color_choice_mode = "forward"
        self.random_seed = random_seed
        self._traverse_rng = random.Random(random_seed)
        self._color_rng = random.Random(random_seed)

        self.node_ids: List[int] = []
        self.available_colors: List[int] = []
        self.node_color: Dict[int, int] = {}
        self.current_payoff: Dict[int, int] = {}

        self._step_sequence: List[int] = []
        self._step_index = 0
        self._step_round = 1
        self._step_changed_this_round = False
        self._step_finished = False

        self._rebuild_state()

    def _rebuild_state(self) -> None:
        self.node_ids = sorted(node.GetId() for node in self.graph.Nodes())
        self.node_num = len(self.node_ids)
        self.available_colors = list(self.node_ids)
        self.init_coloring(color_mode=self.color_mode)

    def init_coloring(self, color_mode: int = 1) -> None:
        """
        color_mode 1 follows the paper: every vertex starts with its own color.
        color_mode 0 keeps the old experiment mode: all vertices start at color 0.
        """
        self.color_mode = color_mode
        if not self.node_ids:
            self.node_ids = sorted(node.GetId() for node in self.graph.Nodes())
        if not self.available_colors:
            self.available_colors = list(self.node_ids)

        if color_mode == 0:
            self.node_color = {node_id: 0 for node_id in self.node_ids}
        else:
            self.node_color = {node_id: node_id for node_id in self.node_ids}

        self.refresh_payoffs()
        self.reset_stepper()

    def get_one_node(self):
        if not self.node_ids:
            raise RuntimeError("Graph has no nodes.")

        if self.node_mode == 0:
            return self.graph.GetNI(self.node_ids[0])
        if self.node_mode == 1:
            return self.graph.GetNI(self.node_ids[-1])

        rng = random.Random(self.random_seed)
        return self.graph.GetNI(rng.choice(self.node_ids))

    def get_neighbors(self, node_id: int) -> List[int]:
        if not self.graph.IsNode(node_id):
            print(f"Warning: Node {node_id} does not exist in the graph.")
            return []

        node = self.graph.GetNI(node_id)
        return [node.GetOutNId(i) for i in range(node.GetDeg())]

    def get_payoff_if(self, node_id: int, color_id: int) -> int:
        if node_id not in self.node_color:
            print(f"Get payoff check: Node {node_id} does not exist in the graph.")
            return 0

        if any(self.node_color.get(neighbor) == color_id for neighbor in self.get_neighbors(node_id)):
            return 0

        return 1 + sum(
            1
            for other_id in self.node_ids
            if other_id != node_id and self.node_color[other_id] == color_id
        )

    def get_payoff(self, node_id: int) -> int:
        return self.get_payoff_if(node_id, self.node_color[node_id])

    def refresh_payoffs(self) -> None:
        self.current_payoff = {node_id: self.get_payoff(node_id) for node_id in self.node_ids}

    def have_same_color_with_neighbours(self, node_id: int, color_id: int) -> bool:
        return any(self.node_color.get(neighbor) == color_id for neighbor in self.get_neighbors(node_id))

    def get_color_sequence(self, randomize: bool = True) -> List[int]:
        colors = sorted(self.available_colors)

        if self.color_choice_mode == "forward":
            return colors

        if self.color_choice_mode == "reverse":
            return list(reversed(colors))

        if self.color_choice_mode == "random":
            shuffled = list(colors)
            if randomize:
                self._color_rng.shuffle(shuffled)
            return shuffled

        raise ValueError(f"Color choice mode {self.color_choice_mode} is not supported.")

    def find_self_improvement(self, node_id: int, randomize: bool = True) -> Optional[Dict[str, int]]:
        original_color = self.node_color[node_id]
        current_payoff = self.get_payoff(node_id)
        best_color = original_color
        best_payoff = current_payoff

        for new_color in self.get_color_sequence(randomize=randomize):
            if new_color == original_color:
                continue

            new_payoff = self.get_payoff_if(node_id, new_color)
            if new_payoff > best_payoff:
                best_color = new_color
                best_payoff = new_payoff

        if best_payoff > current_payoff:
            return {
                "node": node_id,
                "from_color": original_color,
                "to_color": best_color,
                "from_payoff": current_payoff,
                "to_payoff": best_payoff,
            }

        return None

    def improve_payoff(self, node_id: int) -> bool:
        improvement = self.find_self_improvement(node_id)
        if not improvement:
            self.current_payoff[node_id] = self.get_payoff(node_id)
            return False

        self.node_color[node_id] = improvement["to_color"]
        self.refresh_payoffs()
        return True

    def set_node_mode(self, node_mode: int = 0, random_seed: int = 42) -> None:
        self.node_mode = node_mode
        self.random_seed = random_seed
        self._traverse_rng = random.Random(random_seed)
        self._color_rng = random.Random(random_seed)
        self.reset_stepper()

    def set_traverse_mode(self, traverse_mode: str = "forward") -> None:
        if traverse_mode not in {"forward", "reverse", "random"}:
            raise ValueError("traverse_mode must be one of: forward, reverse, random.")
        self.traverse_mode = traverse_mode
        self.reset_stepper()

    def set_color_choice_mode(self, color_choice_mode: str = "forward") -> None:
        if color_choice_mode not in {"forward", "reverse", "random"}:
            raise ValueError("color_choice_mode must be one of: forward, reverse, random.")
        self.color_choice_mode = color_choice_mode
        self.reset_stepper()

    def get_iteration_sequence(self) -> List[int]:
        nodes = sorted(self.node_ids)

        if self.traverse_mode == "forward":
            return nodes

        if self.traverse_mode == "reverse":
            return list(reversed(nodes))

        if self.traverse_mode == "random":
            shuffled = list(nodes)
            self._traverse_rng.shuffle(shuffled)
            return shuffled

        raise ValueError(f"Traverse mode {self.traverse_mode} is not supported.")

    def get_traverse_sequence(self, start_node_id: int) -> List[int]:
        """Backward-compatible wrapper for older callers."""
        nodes = list(self.node_ids)

        if self.traverse_mode == "forward":
            sorted_nodes = sorted(nodes)
            idx = sorted_nodes.index(start_node_id)
            return sorted_nodes[idx:] + sorted_nodes[:idx]

        if self.traverse_mode == "reverse":
            sorted_nodes = sorted(nodes, reverse=True)
            idx = sorted_nodes.index(start_node_id)
            return sorted_nodes[idx:] + sorted_nodes[:idx]

        if self.traverse_mode == "random":
            rng = random.Random(self.random_seed)
            other_nodes = [node_id for node_id in nodes if node_id != start_node_id]
            rng.shuffle(other_nodes)
            return [start_node_id] + other_nodes

        if self.traverse_mode == "bfs":
            visited = {start_node_id}
            queue = [start_node_id]
            sequence = []
            while queue:
                current = queue.pop(0)
                sequence.append(current)
                for neighbor in self.get_neighbors(current):
                    if neighbor not in visited:
                        visited.add(neighbor)
                        queue.append(neighbor)
            sequence.extend([node_id for node_id in nodes if node_id not in visited])
            return sequence

        if self.traverse_mode == "dfs":
            visited = set()
            sequence = []

            def dfs(node_id: int) -> None:
                visited.add(node_id)
                sequence.append(node_id)
                for neighbor in self.get_neighbors(node_id):
                    if neighbor not in visited:
                        dfs(neighbor)

            dfs(start_node_id)
            sequence.extend([node_id for node_id in nodes if node_id not in visited])
            return sequence

        raise ValueError(f"Traverse mode {self.traverse_mode} is not supported.")

    def reset_stepper(self, start_node_id: Optional[int] = None) -> None:
        if not self.node_ids:
            self._step_sequence = []
            self._step_finished = True
            return

        self._traverse_rng = random.Random(self.random_seed)
        self._color_rng = random.Random(self.random_seed)
        self._step_sequence = self.get_iteration_sequence()
        self._step_index = 0
        self._step_round = 1
        self._step_changed_this_round = False
        self._step_finished = False

    def self_improve_step(self) -> Dict[str, object]:
        if not self._step_sequence:
            self.reset_stepper()

        if self._step_finished:
            return {
                "finished": True,
                "message": "Nash Equilibrium already reached.",
                "state": self.get_state(),
            }

        node_id = self._step_sequence[self._step_index]
        before_color = self.node_color[node_id]
        before_payoff = self.get_payoff(node_id)
        improvement = self.find_self_improvement(node_id)
        changed = improvement is not None

        if improvement:
            self.node_color[node_id] = improvement["to_color"]
            self.refresh_payoffs()
            after_color = improvement["to_color"]
            after_payoff = improvement["to_payoff"]
        else:
            self.current_payoff[node_id] = before_payoff
            after_color = before_color
            after_payoff = before_payoff

        self._step_changed_this_round = self._step_changed_this_round or changed
        if self.is_nash_equilibrium():
            self._step_finished = True

        round_finished = False
        if not self._step_finished:
            self._step_index += 1

        if not self._step_finished and self._step_index >= len(self._step_sequence):
            round_finished = True
            if self._step_changed_this_round:
                self._step_round += 1
                self._step_index = 0
                self._step_sequence = self.get_iteration_sequence()
                self._step_changed_this_round = False
            else:
                self._step_finished = True

        return {
            "finished": self._step_finished,
            "round_finished": round_finished,
            "round": self._step_round,
            "node": node_id,
            "changed": changed,
            "before_color": before_color,
            "after_color": after_color,
            "before_payoff": before_payoff,
            "after_payoff": after_payoff,
            "next_node": None if self._step_finished else self._step_sequence[self._step_index],
            "state": self.get_state(),
        }

    def move_to_nash_equilibrium(self) -> None:
        self._traverse_rng = random.Random(self.random_seed)
        self._color_rng = random.Random(self.random_seed)
        iterations = 0

        while True:
            color_changed_this_round = False
            traverse_seq = self.get_iteration_sequence()
            for node_id in traverse_seq:
                color_changed_this_round = self.improve_payoff(node_id) or color_changed_this_round

            iterations += 1
            print(f"iterations: {iterations}")
            self.print_result()

            if not color_changed_this_round:
                print(f"Nash Equilibrium reached after {iterations} iterations.")
                break

    def is_valid_coloring(self) -> bool:
        for node_id in self.node_ids:
            for neighbor in self.get_neighbors(node_id):
                if node_id < neighbor and self.node_color[node_id] == self.node_color[neighbor]:
                    return False
        return True

    def is_nash_equilibrium(self) -> bool:
        return all(
            self.find_self_improvement(node_id, randomize=False) is None
            for node_id in self.node_ids
        )

    def used_colors(self) -> List[int]:
        return sorted(set(self.node_color.values()))

    def get_total_payoff(self) -> int:
        self.refresh_payoffs()
        return sum(self.current_payoff.values())

    def get_state(self) -> Dict[str, object]:
        self.refresh_payoffs()
        return {
            "colors": dict(self.node_color),
            "payoffs": dict(self.current_payoff),
            "used_colors": self.used_colors(),
            "color_count": len(self.used_colors()),
            "total_payoff": sum(self.current_payoff.values()),
            "valid_coloring": self.is_valid_coloring(),
            "nash_equilibrium": self.is_nash_equilibrium(),
            "traverse_mode": self.traverse_mode,
            "color_choice_mode": self.color_choice_mode,
        }

    def print_result(self) -> None:
        self.refresh_payoffs()
        for node_id in self.node_ids:
            print(
                f"node {node_id}, color {self.node_color[node_id]}, "
                f"payoff {self.current_payoff[node_id]}"
            )
        print(f"colors used: {len(self.used_colors())}")
        print(f"total payoff: {sum(self.current_payoff.values())}")

    def load_graph(self, file_path: str) -> None:
        self.graph = snap.LoadEdgeList(snap.PUNGraph, file_path, 0, 1)
        self._rebuild_state()
        print(f"load graph from {file_path}")

    def save_graph(self, file_path: str) -> None:
        snap.SaveEdgeList(self.graph, file_path, "Undirected Graph Saved")
        print(f"graph saved to {file_path}")


def import_template_graph():
    return snap.LoadEdgeList(snap.PUNGraph, TEMPLATE_GRAPH_PATH, 0, 1)


def draw_graph(graph) -> None:
    nx_graph = nx.Graph()
    for edge in graph.Edges():
        nx_graph.add_edge(edge.GetSrcNId(), edge.GetDstNId())

    nx.draw(nx_graph, with_labels=True)
    plt.show()


def test_class() -> None:
    agent = coloring_game()
    agent.load_graph(TEMPLATE_GRAPH_PATH)
    agent.move_to_nash_equilibrium()
    agent.print_result()


def main() -> None:
    test_class()


if __name__ == "__main__":
    main()
