"""
Degree of Saturation
也算是贪心算法了

每一步动态选择最难染色的未染色顶点
未染色顶点 v 的饱和度 = v 的邻居中已经出现的不同颜色数量

1. 在所有未染色顶点中，选择饱和度最大的顶点；
2. 如果饱和度相同，通常选择度数更大的顶点；
3. 给该顶点分配一个合法颜色，通常选择编号最小的可用颜色；
4. 更新其他未染色顶点的饱和度；
    重复，直到所有顶点都被染色
"""
from __future__ import annotations

from typing import Dict, List, Optional, Set, Tuple

import matplotlib.pyplot as plt
import networkx as nx
import snap

GRAPH_PATH = "out/graph.txt"
TEMPLATE_GRAPH_PATH = "src/graph.txt"


class DSATUR:
    """
    DSATUR graph coloring algorithm.

    DSATUR means degree of saturation. At each step, the algorithm selects
    the uncolored vertex whose colored neighborhood uses the largest number
    of distinct colors. Ties are broken by larger graph degree, then smaller
    node id. The selected vertex receives the smallest feasible color.
    """

    def __init__(
        self,
        node_num: int = 5,
        edge_prob: float = 0.5,
    ):
        self.graph = snap.GenRndGnm(
            snap.TUNGraph,
            node_num,
            int(edge_prob * node_num * (node_num - 1) / 2),
        )
        snap.SaveEdgeList(self.graph, GRAPH_PATH, "Random Undirected Graph Generated by Snap.py")
        print(f"random graph saved to {GRAPH_PATH}")

        self.node_num = node_num
        self.edge_prob = edge_prob

        self.node_ids: List[int] = []
        self.adj: Dict[int, Set[int]] = {}
        self.edges: List[Tuple[int, int]] = []
        self.node_color: Dict[int, int] = {}

        self._rebuild_state()

    def _rebuild_state(self) -> None:
        self.node_ids = sorted(node.GetId() for node in self.graph.Nodes())
        self.node_num = len(self.node_ids)
        self.adj = {node_id: set() for node_id in self.node_ids}
        self.edges = []

        for edge in self.graph.Edges():
            u = edge.GetSrcNId()
            v = edge.GetDstNId()
            if u == v:
                continue
            self.adj.setdefault(u, set()).add(v)
            self.adj.setdefault(v, set()).add(u)
            self.edges.append((u, v) if u < v else (v, u))

        self.edges = sorted(set(self.edges))
        self.node_color = {}

    def get_neighbors(self, node_id: int) -> List[int]:
        if node_id not in self.adj:
            print(f"Warning: Node {node_id} does not exist in the graph.")
            return []
        return sorted(self.adj[node_id])

    def _saturation_degree(self, node_id: int, coloring: Dict[int, int]) -> int:
        return len({
            coloring[neighbor]
            for neighbor in self.adj[node_id]
            if neighbor in coloring
        })

    def _select_next_node(self, uncolored: Set[int], coloring: Dict[int, int]) -> int:
        return max(
            uncolored,
            key=lambda node_id: (
                self._saturation_degree(node_id, coloring),
                len(self.adj[node_id]),
                -node_id,
            ),
        )

    def _smallest_feasible_color(self, node_id: int, coloring: Dict[int, int]) -> int:
        forbidden_colors = {
            coloring[neighbor]
            for neighbor in self.adj[node_id]
            if neighbor in coloring
        }

        color_id = 1
        while color_id in forbidden_colors:
            color_id += 1
        return color_id

    def solve(self, verbose: bool = False) -> Tuple[Dict[int, int], int]:
        coloring: Dict[int, int] = {}
        uncolored = set(self.node_ids)
        step = 0

        while uncolored:
            node_id = self._select_next_node(uncolored, coloring)
            color_id = self._smallest_feasible_color(node_id, coloring)

            coloring[node_id] = color_id
            uncolored.remove(node_id)
            step += 1

            if verbose:
                saturation = self._saturation_degree(node_id, coloring)
                print(
                    f"[Step {step}] node={node_id}, color={color_id}, "
                    f"saturation={saturation}, degree={len(self.adj[node_id])}"
                )

        self.node_color = dict(sorted(coloring.items()))
        return dict(self.node_color), len(self.used_colors())

    def count_conflicting_edges(self, coloring: Optional[Dict[int, int]] = None) -> int:
        coloring = coloring or self.node_color
        return sum(1 for u, v in self.edges if coloring.get(u) == coloring.get(v))

    def is_valid_coloring(self, coloring: Optional[Dict[int, int]] = None) -> bool:
        return self.count_conflicting_edges(coloring) == 0

    def used_colors(self) -> List[int]:
        return sorted(set(self.node_color.values()))

    def get_state(self) -> Dict[str, object]:
        return {
            "colors": dict(self.node_color),
            "used_colors": self.used_colors(),
            "color_count": len(self.used_colors()),
            "conflicting_edges": self.count_conflicting_edges(),
            "valid_coloring": self.is_valid_coloring(),
        }

    def print_result(self) -> None:
        if not self.node_color:
            print("No coloring result.")
            return

        print(f"colors used: {len(self.used_colors())}")
        print(f"conflicting edges: {self.count_conflicting_edges()}")
        for node_id in sorted(self.node_color):
            print(f"node {node_id}, color {self.node_color[node_id]}")

    def load_graph(self, file_path: str) -> None:
        self.graph = snap.LoadEdgeList(snap.PUNGraph, file_path, 0, 1)
        self._rebuild_state()
        print(f"load graph from {file_path}")

    def save_graph(self, file_path: str) -> None:
        snap.SaveEdgeList(self.graph, file_path, "Undirected Graph Saved")
        print(f"graph saved to {file_path}")


def import_template_graph():
    return snap.LoadEdgeList(snap.PUNGraph, TEMPLATE_GRAPH_PATH, 0, 1)


def draw_graph(graph) -> None:
    nx_graph = nx.Graph()
    for edge in graph.Edges():
        nx_graph.add_edge(edge.GetSrcNId(), edge.GetDstNId())

    nx.draw(nx_graph, with_labels=True)
    plt.show()


Dsatur = DSATUR
dsatur = DSATUR


def test_class() -> None:
    agent = DSATUR()
    agent.load_graph(TEMPLATE_GRAPH_PATH)
    agent.solve(verbose=True)
    agent.print_result()


def main() -> None:
    test_class()


if __name__ == "__main__":
    main()
