"""
1. 随机所有顶点颜色
2. 检查冲突边
    while 冲突 > 0
    修改冲突其中的一个颜色，禁忌表；一定时间内禁止改回颜色
不能保证一定找到最优解

"""
from __future__ import annotations

import random
from typing import Dict, List, Optional, Set, Tuple

import matplotlib.pyplot as plt
import networkx as nx
import snap

GRAPH_PATH = "out/graph.txt"
TEMPLATE_GRAPH_PATH = "src/graph.txt"


class TabuCol:
    """
    Graph coloring with the TabuCol tabu-search algorithm.

    TabuCol solves the fixed-k coloring problem by minimizing conflicting
    edges. The public solve method repeatedly calls TabuCol with decreasing
    color limits and keeps the best feasible coloring found.
    """

    def __init__(
        self,
        node_num: int = 5,
        edge_prob: float = 0.5,
        random_seed: int = 42,
        max_iterations: int = 10000,
        max_restarts: int = 20,
        tabu_tenure_base: int = 7,
        tabu_tenure_alpha: float = 0.6,
    ):
        self.graph = snap.GenRndGnm(
            snap.TUNGraph,
            node_num,
            int(edge_prob * node_num * (node_num - 1) / 2),
        )
        snap.SaveEdgeList(self.graph, GRAPH_PATH, "Random Undirected Graph Generated by Snap.py")
        print(f"random graph saved to {GRAPH_PATH}")

        self.node_num = node_num
        self.edge_prob = edge_prob
        self.random_seed = random_seed
        self.max_iterations = max_iterations
        self.max_restarts = max_restarts
        self.tabu_tenure_base = tabu_tenure_base
        self.tabu_tenure_alpha = tabu_tenure_alpha
        self.rng = random.Random(random_seed)

        self.node_ids: List[int] = []
        self.adj: Dict[int, Set[int]] = {}
        self.edges: List[Tuple[int, int]] = []
        self.node_color: Dict[int, int] = {}
        self.best_coloring: Dict[int, int] = {}
        self.best_color_count: int = 0
        self.best_conflicts: int = 10**9

        self._rebuild_state()

    def _rebuild_state(self) -> None:
        self.node_ids = sorted(node.GetId() for node in self.graph.Nodes())
        self.node_num = len(self.node_ids)

        self.adj = {node_id: set() for node_id in self.node_ids}
        self.edges = []

        for edge in self.graph.Edges():
            u = edge.GetSrcNId()
            v = edge.GetDstNId()
            if u == v:
                continue
            self.adj.setdefault(u, set()).add(v)
            self.adj.setdefault(v, set()).add(u)
            self.edges.append((u, v) if u < v else (v, u))

        self.edges = sorted(set(self.edges))
        self.node_color = {node_id: 1 for node_id in self.node_ids}
        self.best_coloring = {}
        self.best_color_count = 0
        self.best_conflicts = self.count_conflicting_edges(self.node_color)

    def get_neighbors(self, node_id: int) -> List[int]:
        if node_id not in self.adj:
            print(f"Warning: Node {node_id} does not exist in the graph.")
            return []
        return sorted(self.adj[node_id])

    def _random_coloring(self, color_count: int) -> Dict[int, int]:
        return {
            node_id: self.rng.randint(1, color_count)
            for node_id in self.node_ids
        }

    def _initial_coloring(self, color_count: int) -> Dict[int, int]:
        if color_count >= self.node_num:
            return {
                node_id: index + 1
                for index, node_id in enumerate(self.node_ids)
            }
        return self._random_coloring(color_count)

    def count_conflicting_edges(self, coloring: Optional[Dict[int, int]] = None) -> int:
        coloring = coloring or self.node_color
        return sum(1 for u, v in self.edges if coloring.get(u) == coloring.get(v))

    def _conflicting_vertices(self, coloring: Dict[int, int]) -> Set[int]:
        conflicting: Set[int] = set()
        for u, v in self.edges:
            if coloring[u] == coloring[v]:
                conflicting.add(u)
                conflicting.add(v)
        return conflicting

    def _move_delta(self, coloring: Dict[int, int], node_id: int, new_color: int) -> int:
        old_color = coloring[node_id]
        old_conflicts = 0
        new_conflicts = 0

        for neighbor in self.adj[node_id]:
            neighbor_color = coloring[neighbor]
            if neighbor_color == old_color:
                old_conflicts += 1
            if neighbor_color == new_color:
                new_conflicts += 1

        return new_conflicts - old_conflicts

    def _tabu_tenure(self, conflict_count: int) -> int:
        dynamic_part = int(self.tabu_tenure_alpha * conflict_count)
        return dynamic_part + self.rng.randint(0, self.tabu_tenure_base)

    def _select_move(
        self,
        coloring: Dict[int, int],
        color_count: int,
        conflict_count: int,
        best_conflicts: int,
        tabu_until: Dict[Tuple[int, int], int],
        iteration: int,
    ) -> Optional[Tuple[int, int, int]]:
        conflicting_vertices = list(self._conflicting_vertices(coloring))
        self.rng.shuffle(conflicting_vertices)

        best_moves: List[Tuple[int, int, int]] = []
        best_delta: Optional[int] = None
        fallback_moves: List[Tuple[int, int, int]] = []
        fallback_delta: Optional[int] = None

        for node_id in conflicting_vertices:
            old_color = coloring[node_id]
            colors = list(range(1, color_count + 1))
            self.rng.shuffle(colors)

            for new_color in colors:
                if new_color == old_color:
                    continue

                delta = self._move_delta(coloring, node_id, new_color)
                projected_conflicts = conflict_count + delta
                is_tabu = tabu_until.get((node_id, new_color), 0) > iteration
                aspiration = projected_conflicts < best_conflicts
                move = (node_id, new_color, delta)

                if fallback_delta is None or delta < fallback_delta:
                    fallback_delta = delta
                    fallback_moves = [move]
                elif delta == fallback_delta:
                    fallback_moves.append(move)

                if is_tabu and not aspiration:
                    continue

                if best_delta is None or delta < best_delta:
                    best_delta = delta
                    best_moves = [move]
                elif delta == best_delta:
                    best_moves.append(move)

        if best_moves:
            return self.rng.choice(best_moves)
        if fallback_moves:
            return self.rng.choice(fallback_moves)
        return None

    def tabucol(
        self,
        color_count: int,
        max_iterations: Optional[int] = None,
        verbose: bool = False,
    ) -> Tuple[Optional[Dict[int, int]], int]:
        """
        Run TabuCol for a fixed number of colors.

        Returns a feasible coloring and 0 conflicts on success. If the search
        does not find a feasible coloring, returns None and the best conflict
        count reached by this run.
        """
        if color_count <= 0:
            raise ValueError("color_count must be positive.")
        if not self.node_ids:
            return {}, 0

        max_iterations = max_iterations or self.max_iterations
        coloring = self._initial_coloring(color_count)
        conflict_count = self.count_conflicting_edges(coloring)
        best_coloring = dict(coloring)
        best_conflicts = conflict_count
        tabu_until: Dict[Tuple[int, int], int] = {}

        if conflict_count == 0:
            return self._compact_coloring(coloring), 0

        for iteration in range(1, max_iterations + 1):
            selected = self._select_move(
                coloring=coloring,
                color_count=color_count,
                conflict_count=conflict_count,
                best_conflicts=best_conflicts,
                tabu_until=tabu_until,
                iteration=iteration,
            )
            if selected is None:
                break

            node_id, new_color, delta = selected
            old_color = coloring[node_id]
            coloring[node_id] = new_color
            conflict_count += delta
            tabu_until[(node_id, old_color)] = iteration + self._tabu_tenure(conflict_count)

            if conflict_count < best_conflicts:
                best_conflicts = conflict_count
                best_coloring = dict(coloring)

                if verbose:
                    print(
                        f"[k={color_count}] iteration={iteration}, "
                        f"best_conflicts={best_conflicts}"
                    )

                if best_conflicts == 0:
                    return self._compact_coloring(best_coloring), 0

        return None, best_conflicts

    def solve_fixed_k(
        self,
        color_count: int,
        max_iterations: Optional[int] = None,
        max_restarts: Optional[int] = None,
        verbose: bool = False,
    ) -> Tuple[Optional[Dict[int, int]], int]:
        max_restarts = max_restarts or self.max_restarts
        best_conflicts = 10**9

        for restart in range(1, max_restarts + 1):
            coloring, conflicts = self.tabucol(
                color_count=color_count,
                max_iterations=max_iterations,
                verbose=verbose,
            )

            if coloring is not None:
                if verbose:
                    print(f"[k={color_count}] feasible coloring found at restart {restart}")
                return coloring, 0

            best_conflicts = min(best_conflicts, conflicts)

        return None, best_conflicts

    def solve(
        self,
        max_colors: Optional[int] = None,
        min_colors: int = 1,
        max_iterations: Optional[int] = None,
        max_restarts: Optional[int] = None,
        verbose: bool = False,
    ) -> Tuple[Dict[int, int], int]:
        """
        Search for a coloring with as few colors as TabuCol can find.

        The search starts from max_colors, then tries one fewer color each
        time. When TabuCol fails for k colors, the previous feasible coloring
        is returned.
        """
        if min_colors <= 0:
            raise ValueError("min_colors must be positive.")
        if not self.node_ids:
            self.node_color = {}
            return {}, 0

        upper_bound = max_colors or self.node_num
        upper_bound = min(upper_bound, self.node_num)
        if upper_bound < min_colors:
            raise ValueError("max_colors must be greater than or equal to min_colors.")

        self.rng = random.Random(self.random_seed)
        best_coloring: Dict[int, int] = {}
        best_color_count = 0
        last_failure_conflicts = 0

        for color_count in range(upper_bound, min_colors - 1, -1):
            coloring, conflicts = self.solve_fixed_k(
                color_count=color_count,
                max_iterations=max_iterations,
                max_restarts=max_restarts,
                verbose=verbose,
            )

            if coloring is None:
                last_failure_conflicts = conflicts
                if verbose:
                    print(
                        f"[k={color_count}] no feasible coloring found, "
                        f"best_conflicts={conflicts}"
                    )
                break

            best_coloring = coloring
            best_color_count = len(set(coloring.values()))
            if verbose:
                print(f"[k={color_count}] accepted, used_colors={best_color_count}")

        if not best_coloring:
            fallback = self._compact_coloring({
                node_id: index + 1
                for index, node_id in enumerate(self.node_ids)
            })
            best_coloring = fallback
            best_color_count = len(set(fallback.values()))
            last_failure_conflicts = self.count_conflicting_edges(fallback)

        self.node_color = dict(best_coloring)
        self.best_coloring = dict(best_coloring)
        self.best_color_count = best_color_count
        self.best_conflicts = last_failure_conflicts
        return dict(best_coloring), best_color_count

    def color_graph(
        self,
        max_colors: Optional[int] = None,
        min_colors: int = 1,
        max_iterations: Optional[int] = None,
        max_restarts: Optional[int] = None,
        verbose: bool = False,
    ) -> Tuple[Dict[int, int], int]:
        return self.solve(
            max_colors=max_colors,
            min_colors=min_colors,
            max_iterations=max_iterations,
            max_restarts=max_restarts,
            verbose=verbose,
        )

    def _compact_coloring(self, coloring: Dict[int, int]) -> Dict[int, int]:
        color_map = {
            color_id: index + 1
            for index, color_id in enumerate(sorted(set(coloring.values())))
        }
        return {
            node_id: color_map[coloring[node_id]]
            for node_id in sorted(coloring)
        }

    def is_valid_coloring(self, coloring: Optional[Dict[int, int]] = None) -> bool:
        return self.count_conflicting_edges(coloring) == 0

    def used_colors(self) -> List[int]:
        return sorted(set(self.node_color.values()))

    def get_state(self) -> Dict[str, object]:
        return {
            "colors": dict(self.node_color),
            "used_colors": self.used_colors(),
            "color_count": len(self.used_colors()),
            "conflicting_edges": self.count_conflicting_edges(),
            "valid_coloring": self.is_valid_coloring(),
        }

    def print_result(self) -> None:
        if not self.node_color:
            print("No coloring result.")
            return

        print(f"colors used: {len(self.used_colors())}")
        print(f"conflicting edges: {self.count_conflicting_edges()}")
        for node_id in sorted(self.node_color):
            print(f"node {node_id}, color {self.node_color[node_id]}")

    def load_graph(self, file_path: str) -> None:
        self.graph = snap.LoadEdgeList(snap.PUNGraph, file_path, 0, 1)
        self._rebuild_state()
        print(f"load graph from {file_path}")

    def save_graph(self, file_path: str) -> None:
        snap.SaveEdgeList(self.graph, file_path, "Undirected Graph Saved")
        print(f"graph saved to {file_path}")


def import_template_graph():
    return snap.LoadEdgeList(snap.PUNGraph, TEMPLATE_GRAPH_PATH, 0, 1)


def draw_graph(graph) -> None:
    nx_graph = nx.Graph()
    for edge in graph.Edges():
        nx_graph.add_edge(edge.GetSrcNId(), edge.GetDstNId())

    nx.draw(nx_graph, with_labels=True)
    plt.show()


TabuCal = TabuCol
tabucal = TabuCol


def test_class() -> None:
    agent = TabuCol(random_seed=7, max_iterations=5000, max_restarts=30)
    agent.load_graph(TEMPLATE_GRAPH_PATH)
    agent.solve(verbose=True)
    agent.print_result()


def main() -> None:
    test_class()


if __name__ == "__main__":
    main()
