"""
1. 随机所有顶点颜色
2. 检查冲突边
    while 冲突 > 0
    修改冲突其中的一个颜色，禁忌表；一定时间内禁止改回颜色
不能保证一定找到最优解

"""
from __future__ import annotations

import random
from typing import Dict, List, Optional, Set, Tuple

import matplotlib.pyplot as plt
import networkx as nx
import snap

GRAPH_PATH = "out/graph.txt"
TEMPLATE_GRAPH_PATH = "src/graph.txt"


class TabuCol:
    def __init__(
        self,
        node_num: int = 5,
        edge_prob: float = 0.5,
        random_seed: int = 42,
        max_iterations: int = 10000,
        max_restarts: int = 20,
        tabu_tenure_base: int = 10,
        tabu_tenure_alpha: float = 0.6,
    ):
        self.graph = snap.GenRndGnm(
            snap.TUNGraph,
            node_num,
            int(edge_prob * node_num * (node_num - 1) / 2),
        )
        snap.SaveEdgeList(self.graph, GRAPH_PATH, "Random Undirected Graph Generated by Snap.py")
        print(f"random graph saved to {GRAPH_PATH}")

        self.node_num = node_num
        self.edge_prob = edge_prob
        self.random_seed = random_seed
        self.max_iterations = max_iterations
        self.max_restarts = max_restarts
        self.tabu_tenure_base = tabu_tenure_base
        self.tabu_tenure_alpha = tabu_tenure_alpha
        self.rng = random.Random(random_seed)

        self.node_ids: List[int] = []
        self.adj: Dict[int, Set[int]] = {}
        self.edges: List[Tuple[int, int]] = []
        self.node_color: Dict[int, int] = {}
        self.best_coloring: Dict[int, int] = {}
        self.best_color_count: int = 0
        self.best_conflicts: int = 10**9
        self.last_run_best_coloring: Dict[int, int] = {}
        self.last_run_best_conflicts: int = 10**9
        self.last_fixed_k_best_coloring: Dict[int, int] = {}
        self.last_failure_conflicts: int = 0

        self._rebuild_state()

    def _rebuild_state(self) -> None:
        self.node_ids = sorted(node.GetId() for node in self.graph.Nodes())
        self.node_num = len(self.node_ids)

        self.adj = {node_id: set() for node_id in self.node_ids}
        self.edges = []

        for edge in self.graph.Edges():
            u = edge.GetSrcNId()
            v = edge.GetDstNId()
            if u == v:
                continue
            self.adj.setdefault(u, set()).add(v)
            self.adj.setdefault(v, set()).add(u)
            self.edges.append((u, v) if u < v else (v, u))

        self.edges = sorted(set(self.edges))
        self.node_color = {node_id: 1 for node_id in self.node_ids}
        self.best_coloring = {}
        self.best_color_count = 0
        self.best_conflicts = self.count_conflicting_edges(self.node_color)
        self.last_run_best_coloring = {}
        self.last_run_best_conflicts = 10**9
        self.last_fixed_k_best_coloring = {}
        self.last_failure_conflicts = 0

    def get_neighbors(self, node_id: int) -> List[int]:
        if node_id not in self.adj:
            print(f"Warning: Node {node_id} does not exist in the graph.")
            return []
        return sorted(self.adj[node_id])

    def _random_coloring(self, color_count: int) -> Dict[int, int]:
        return {
            node_id: self.rng.randint(1, color_count)
            for node_id in self.node_ids
        }

    def _dsatur_coloring(self) -> Dict[int, int]:
        """Build a deterministic feasible coloring to obtain an upper bound."""
        coloring: Dict[int, int] = {}
        uncolored = set(self.node_ids)

        while uncolored:
            node_id = max(
                uncolored,
                key=lambda candidate: (
                    len({
                        coloring[neighbor]
                        for neighbor in self.adj[candidate]
                        if neighbor in coloring
                    }),
                    len(self.adj[candidate]),
                    -candidate,
                ),
            )
            forbidden_colors = {
                coloring[neighbor]
                for neighbor in self.adj[node_id]
                if neighbor in coloring
            }
            color_id = 1
            while color_id in forbidden_colors:
                color_id += 1

            coloring[node_id] = color_id
            uncolored.remove(node_id)

        return self._compact_coloring(coloring)

    def _reduce_coloring(
        self,
        coloring: Dict[int, int],
        target_color_count: int,
    ) -> Dict[int, int]:
        """Construct a warm start by removing color classes from a feasible coloring."""
        if target_color_count <= 0:
            raise ValueError("target_color_count must be positive.")
        if set(coloring) != set(self.node_ids):
            raise ValueError("coloring must assign every graph vertex.")

        reduced = self._compact_coloring(coloring)
        while len(set(reduced.values())) > target_color_count:
            color_classes: Dict[int, List[int]] = {}
            for node_id, color_id in reduced.items():
                color_classes.setdefault(color_id, []).append(node_id)

            removed_color = min(
                color_classes,
                key=lambda color_id: (len(color_classes[color_id]), color_id),
            )
            remaining_colors = sorted(
                color_id for color_id in color_classes if color_id != removed_color
            )
            removed_vertices = sorted(
                color_classes[removed_color],
                key=lambda node_id: (-len(self.adj[node_id]), node_id),
            )

            for node_id in removed_vertices:
                conflict_by_color = {
                    color_id: sum(
                        1
                        for neighbor in self.adj[node_id]
                        if reduced[neighbor] == color_id
                    )
                    for color_id in remaining_colors
                }
                minimum_conflicts = min(conflict_by_color.values())
                best_colors = [
                    color_id
                    for color_id, conflicts in conflict_by_color.items()
                    if conflicts == minimum_conflicts
                ]
                reduced[node_id] = self.rng.choice(best_colors)

            reduced = self._compact_coloring(reduced)

        return reduced

    def _initial_coloring(
        self,
        color_count: int,
        initial_coloring: Optional[Dict[int, int]] = None,
    ) -> Dict[int, int]:
        if initial_coloring is not None:
            if set(initial_coloring) != set(self.node_ids):
                raise ValueError("initial_coloring must assign every graph vertex.")
            if any(
                color_id < 1 or color_id > color_count
                for color_id in initial_coloring.values()
            ):
                raise ValueError(
                    "initial_coloring colors must be between 1 and color_count."
                )
            return dict(initial_coloring)

        if color_count >= self.node_num:
            return {
                node_id: index + 1
                for index, node_id in enumerate(self.node_ids)
            }
        return self._random_coloring(color_count)

    def count_conflicting_edges(self, coloring: Optional[Dict[int, int]] = None) -> int:
        if coloring is None:
            coloring = self.node_color
        return sum(1 for u, v in self.edges if coloring.get(u) == coloring.get(v))

    def _conflicting_vertices(self, coloring: Dict[int, int]) -> Set[int]:
        conflicting: Set[int] = set()
        for u, v in self.edges:
            if coloring[u] == coloring[v]:
                conflicting.add(u)
                conflicting.add(v)
        return conflicting

    def _build_conflict_state(
        self,
        coloring: Dict[int, int],
        color_count: int,
    ) -> Tuple[Dict[int, List[int]], Set[int], int]:
        """Build Gamma[v][c], the conflict set, and the total conflict count."""
        conflict_table = {
            node_id: [0] * (color_count + 1)
            for node_id in self.node_ids
        }
        for u, v in self.edges:
            conflict_table[u][coloring[v]] += 1
            conflict_table[v][coloring[u]] += 1

        conflicting_vertices = {
            node_id
            for node_id in self.node_ids
            if conflict_table[node_id][coloring[node_id]] > 0
        }
        conflict_count = sum(
            conflict_table[node_id][coloring[node_id]]
            for node_id in self.node_ids
        ) // 2
        return conflict_table, conflicting_vertices, conflict_count

    def _move_delta(
        self,
        coloring: Dict[int, int],
        node_id: int,
        new_color: int,
        conflict_table: Optional[Dict[int, List[int]]] = None,
    ) -> int:
        old_color = coloring[node_id]
        if conflict_table is not None:
            return (
                conflict_table[node_id][new_color]
                - conflict_table[node_id][old_color]
            )

        old_conflicts = 0
        new_conflicts = 0

        for neighbor in self.adj[node_id]:
            neighbor_color = coloring[neighbor]
            if neighbor_color == old_color:
                old_conflicts += 1
            if neighbor_color == new_color:
                new_conflicts += 1

        return new_conflicts - old_conflicts

    def _apply_move(
        self,
        coloring: Dict[int, int],
        conflict_table: Dict[int, List[int]],
        conflicting_vertices: Set[int],
        node_id: int,
        new_color: int,
    ) -> int:
        """Apply one recoloring and incrementally update all conflict state."""
        old_color = coloring[node_id]
        delta = self._move_delta(
            coloring,
            node_id,
            new_color,
            conflict_table=conflict_table,
        )
        coloring[node_id] = new_color

        for neighbor in self.adj[node_id]:
            conflict_table[neighbor][old_color] -= 1
            conflict_table[neighbor][new_color] += 1
            if conflict_table[neighbor][coloring[neighbor]] > 0:
                conflicting_vertices.add(neighbor)
            else:
                conflicting_vertices.discard(neighbor)

        if conflict_table[node_id][new_color] > 0:
            conflicting_vertices.add(node_id)
        else:
            conflicting_vertices.discard(node_id)

        return delta

    def _tabu_tenure(self, conflicting_vertex_count: int) -> int:
        """Return Random(A) + alpha * nbCFL from Galinier and Hao."""
        random_part = (
            self.rng.randrange(self.tabu_tenure_base)
            if self.tabu_tenure_base > 0
            else 0
        )
        dynamic_part = int(
            self.tabu_tenure_alpha * conflicting_vertex_count
        )
        return max(1, random_part + dynamic_part)

    def _select_move(
        self,
        coloring: Dict[int, int],
        color_count: int,
        conflict_count: int,
        best_conflicts: int,
        conflict_table: Dict[int, List[int]],
        conflicting_vertices: Set[int],
        tabu_until: Dict[Tuple[int, int], int],
        iteration: int,
    ) -> Optional[Tuple[int, int, int]]:
        best_moves: List[Tuple[int, int, int]] = []
        best_delta: Optional[int] = None
        fallback_moves: List[Tuple[int, int, int]] = []
        fallback_delta: Optional[int] = None

        for node_id in sorted(conflicting_vertices):
            old_color = coloring[node_id]
            for new_color in range(1, color_count + 1):
                if new_color == old_color:
                    continue

                delta = self._move_delta(
                    coloring,
                    node_id,
                    new_color,
                    conflict_table=conflict_table,
                )
                projected_conflicts = conflict_count + delta
                is_tabu = tabu_until.get((node_id, new_color), 0) > iteration
                aspiration = projected_conflicts < best_conflicts
                move = (node_id, new_color, delta)

                if fallback_delta is None or delta < fallback_delta:
                    fallback_delta = delta
                    fallback_moves = [move]
                elif delta == fallback_delta:
                    fallback_moves.append(move)

                if is_tabu and not aspiration:
                    continue

                if best_delta is None or delta < best_delta:
                    best_delta = delta
                    best_moves = [move]
                elif delta == best_delta:
                    best_moves.append(move)

        if best_moves:
            return self.rng.choice(best_moves)
        if fallback_moves:
            return self.rng.choice(fallback_moves)
        return None

    def tabucol(
        self,
        color_count: int,
        max_iterations: Optional[int] = None,
        verbose: bool = False,
        initial_coloring: Optional[Dict[int, int]] = None,
    ) -> Tuple[Optional[Dict[int, int]], int]:

        if color_count <= 0:
            raise ValueError("color_count must be positive.")
        if not self.node_ids:
            self.last_run_best_coloring = {}
            self.last_run_best_conflicts = 0
            return {}, 0

        if max_iterations is None:
            max_iterations = self.max_iterations
        if max_iterations <= 0:
            raise ValueError("max_iterations must be positive.")

        coloring = self._initial_coloring(
            color_count,
            initial_coloring=initial_coloring,
        )
        conflict_table, conflicting_vertices, conflict_count = (
            self._build_conflict_state(coloring, color_count)
        )
        best_coloring = dict(coloring)
        best_conflicts = conflict_count
        tabu_until: Dict[Tuple[int, int], int] = {}

        if conflict_count == 0:
            feasible = self._compact_coloring(coloring)
            self.last_run_best_coloring = dict(feasible)
            self.last_run_best_conflicts = 0
            return feasible, 0

        for iteration in range(1, max_iterations + 1):
            selected = self._select_move(
                coloring=coloring,
                color_count=color_count,
                conflict_count=conflict_count,
                best_conflicts=best_conflicts,
                conflict_table=conflict_table,
                conflicting_vertices=conflicting_vertices,
                tabu_until=tabu_until,
                iteration=iteration,
            )
            if selected is None:
                break

            node_id, new_color, delta = selected
            old_color = coloring[node_id]
            applied_delta = self._apply_move(
                coloring=coloring,
                conflict_table=conflict_table,
                conflicting_vertices=conflicting_vertices,
                node_id=node_id,
                new_color=new_color,
            )
            if applied_delta != delta:
                raise RuntimeError("incremental conflict delta became inconsistent.")
            conflict_count += applied_delta
            tabu_until[(node_id, old_color)] = (
                iteration + self._tabu_tenure(len(conflicting_vertices))
            )

            improved = conflict_count < best_conflicts
            if conflict_count <= best_conflicts:
                best_conflicts = conflict_count
                best_coloring = dict(coloring)

                if verbose and improved:
                    print(
                        f"[k={color_count}] iteration={iteration}, "
                        f"best_conflicts={best_conflicts}"
                    )

                if best_conflicts == 0:
                    feasible = self._compact_coloring(best_coloring)
                    self.last_run_best_coloring = dict(feasible)
                    self.last_run_best_conflicts = 0
                    return feasible, 0

        self.last_run_best_coloring = dict(best_coloring)
        self.last_run_best_conflicts = best_conflicts
        return None, best_conflicts

    def solve_fixed_k(
        self,
        color_count: int,
        max_iterations: Optional[int] = None,
        max_restarts: Optional[int] = None,
        verbose: bool = False,
        initial_coloring: Optional[Dict[int, int]] = None,
    ) -> Tuple[Optional[Dict[int, int]], int]:
        if max_restarts is None:
            max_restarts = self.max_restarts
        if max_restarts <= 0:
            raise ValueError("max_restarts must be positive.")

        best_conflicts = 10**9
        best_failed_coloring: Dict[int, int] = {}

        for restart in range(1, max_restarts + 1):
            coloring, conflicts = self.tabucol(
                color_count=color_count,
                max_iterations=max_iterations,
                verbose=verbose,
                initial_coloring=initial_coloring if restart == 1 else None,
            )

            if coloring is not None:
                self.last_fixed_k_best_coloring = dict(coloring)
                if verbose:
                    print(f"[k={color_count}] feasible coloring found at restart {restart}")
                return coloring, 0

            if conflicts <= best_conflicts:
                best_conflicts = conflicts
                best_failed_coloring = dict(self.last_run_best_coloring)

        self.last_fixed_k_best_coloring = best_failed_coloring
        return None, best_conflicts

    def solve(
        self,
        max_colors: Optional[int] = None,
        min_colors: int = 1,
        max_iterations: Optional[int] = None,
        max_restarts: Optional[int] = None,
        verbose: bool = False,
    ) -> Tuple[Dict[int, int], int]:

        if min_colors <= 0:
            raise ValueError("min_colors must be positive.")
        if not self.node_ids:
            self.node_color = {}
            return {}, 0

        if max_colors is not None and max_colors <= 0:
            raise ValueError("max_colors must be positive.")
        upper_bound = self.node_num if max_colors is None else max_colors
        upper_bound = min(upper_bound, self.node_num)
        if upper_bound < min_colors:
            raise ValueError("max_colors must be greater than or equal to min_colors.")

        self.rng = random.Random(self.random_seed)
        best_coloring = self._dsatur_coloring()
        best_color_count = len(set(best_coloring.values()))
        last_failure_conflicts = 0

        if verbose:
            print(f"[DSATUR] feasible upper bound={best_color_count}")

        color_count = min(upper_bound, best_color_count - 1)
        while color_count >= min_colors:
            warm_start = self._reduce_coloring(best_coloring, color_count)
            coloring, conflicts = self.solve_fixed_k(
                color_count=color_count,
                max_iterations=max_iterations,
                max_restarts=max_restarts,
                verbose=verbose,
                initial_coloring=warm_start,
            )

            if coloring is None:
                last_failure_conflicts = conflicts
                if verbose:
                    print(
                        f"[k={color_count}] no feasible coloring found, "
                        f"best_conflicts={conflicts}"
                    )
                break

            best_coloring = coloring
            best_color_count = len(set(coloring.values()))
            if verbose:
                print(f"[k={color_count}] accepted, used_colors={best_color_count}")
            color_count = best_color_count - 1

        self.node_color = dict(best_coloring)
        self.best_coloring = dict(best_coloring)
        self.best_color_count = best_color_count
        self.best_conflicts = 0
        self.last_failure_conflicts = last_failure_conflicts
        return dict(best_coloring), best_color_count

    def color_graph(
        self,
        max_colors: Optional[int] = None,
        min_colors: int = 1,
        max_iterations: Optional[int] = None,
        max_restarts: Optional[int] = None,
        verbose: bool = False,
    ) -> Tuple[Dict[int, int], int]:
        return self.solve(
            max_colors=max_colors,
            min_colors=min_colors,
            max_iterations=max_iterations,
            max_restarts=max_restarts,
            verbose=verbose,
        )

    def _compact_coloring(self, coloring: Dict[int, int]) -> Dict[int, int]:
        color_map = {
            color_id: index + 1
            for index, color_id in enumerate(sorted(set(coloring.values())))
        }
        return {
            node_id: color_map[coloring[node_id]]
            for node_id in sorted(coloring)
        }

    def is_valid_coloring(self, coloring: Optional[Dict[int, int]] = None) -> bool:
        return self.count_conflicting_edges(coloring) == 0

    def used_colors(self) -> List[int]:
        return sorted(set(self.node_color.values()))

    def get_state(self) -> Dict[str, object]:
        return {
            "colors": dict(self.node_color),
            "used_colors": self.used_colors(),
            "color_count": len(self.used_colors()),
            "conflicting_edges": self.count_conflicting_edges(),
            "valid_coloring": self.is_valid_coloring(),
        }

    def print_result(self) -> None:
        if not self.node_color:
            print("No coloring result.")
            return

        print(f"colors used: {len(self.used_colors())}")
        print(f"conflicting edges: {self.count_conflicting_edges()}")
        for node_id in sorted(self.node_color):
            print(f"node {node_id}, color {self.node_color[node_id]}")

    def load_graph(self, file_path: str) -> None:
        self.graph = snap.LoadEdgeList(snap.PUNGraph, file_path, 0, 1)
        self._rebuild_state()
        print(f"load graph from {file_path}")

    def save_graph(self, file_path: str) -> None:
        snap.SaveEdgeList(self.graph, file_path, "Undirected Graph Saved")
        print(f"graph saved to {file_path}")


def import_template_graph():
    return snap.LoadEdgeList(snap.PUNGraph, TEMPLATE_GRAPH_PATH, 0, 1)


def draw_graph(graph) -> None:
    nx_graph = nx.Graph()
    for edge in graph.Edges():
        nx_graph.add_edge(edge.GetSrcNId(), edge.GetDstNId())

    nx.draw(nx_graph, with_labels=True)
    plt.show()


TabuCal = TabuCol
tabucal = TabuCol


def test_class() -> None:
    agent = TabuCol(random_seed=7, max_iterations=5000, max_restarts=30)
    agent.load_graph(TEMPLATE_GRAPH_PATH)
    agent.solve(verbose=True)
    agent.print_result()


def main() -> None:
    test_class()


if __name__ == "__main__":
    main()
