import snap
import os

SAVE_PATH = "out"
TEMPLATE_GRAPH_PATH = "src/graph.txt"

class Undirected_graph():
    def __init__(self, graph_name: str = "ant_ref", node_num: int = 5, edge_prob: float = 0.5):
        self.graph = snap.GenRndGnm(snap.TUNGraph, node_num, int(edge_prob * node_num * (node_num - 1) / 2))

        graph_save_path = os.path.join(SAVE_PATH, graph_name) + ".txt"
        snap.SaveEdgeList(self.graph, graph_save_path, "Random Undirected Graph Generated by Snap.py")
        print(f"random graph saved to {graph_save_path}")

        self.node_num = node_num
        self.edge_prob = edge_prob
        self.graph_name = graph_name

        self.node_color = {}
        self.node_payoff = {}

    def print_result(self):
        for node_id in range(1, self.node_num + 1):
            print(f"node {node_id}, color {self.node_color[node_id]}")
        max_payoff = sum(self.current_payoff)
        print(f"max payoff: {max_payoff}")

    def load_graph(self, file_path: str):
        self.graph = snap.LoadEdgeList(snap.PUNGraph, file_path, 0, 1)
        self.node_num = self.graph.GetNodes()

        print(f"load graph from {file_path}")

    def save_graph(self, file_path: str):
        snap.SaveEdgeList(self.graph, file_path, "Undirected Graph Saved")
        print(f"graph saved to {file_path}")
