import snap

GRAPH_PATH = "out/graph.txt"

class coloring_game():
    def __init__(self, node_num: int, edge_prob: float):

        self.graph = snap.GenRndGnp(snap.TUNGraph, node_num, edge_prob)

        snap.SaveEdgeList(self.graph, GRAPH_PATH, "Random Undirected Graph Generated by Snap.py")
        print(f"random graph saved to {GRAPH_PATH}")


def check_nash_equilibrium() -> bool:


    return True

a = [0] * 10
for i in range(10):
    a[i] = i
print(a)